language: python
python:
    - "2.7"

env:
    - PLATFORMIO_CI_SRC=e-Paper/

install:
    - pip install -U platformio

script:
    - platformio ci --board=<ID_1> --board=<ID_2> --board=<ID_N>
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: gh-pages
